# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

resources:
  repositories:
  - repository: self
    type: git
    ref: master

pool:
  vmImage: ubuntu-latest


steps:
  - checkout: self
    clean: true
  - task: PowerShell@2
    condition: succeeded()
    continueOnError: False
    displayName: 'Provide Download Portal Access'
    enabled: true
    inputs:
      filePath: 'Test1/Version.ps1'
      errorActionPreference: 'continue'